### PR TITLE
Added solution of "Reverse a Stack Using Recursion"

### PR DESCRIPTION
**Pull request by neyhere07**
### FIxes: #37 
Successfully added the solution of <strong>"Reverse a Stack Using Recursion"</strong> under <strong>"O) Stack"</strong> folder. Kindly review this PR/MR.
Thank you!

### CODE REVIEW

**Comment by AnkitMajee** [comment]
Thanks for the thoughtful contribution! 🚀 @neyhere07

**Comment by AnkitMajee** [comment]
@neyhere07 
Do give a Star if this repository helps you in future.
Also this would keep me motivated to maintain for all Problem solving lovers.

**Comment by neyhere07** [comment]
> @neyhere07 Do give a Star if this repository helps you in future. Also this would keep me motivated to maintain for all Problem solving lovers.

Already done! Glad to contribute on this repo, will surely do more contribution in future.

**Comment by neyhere07** [comment]
I request to add label as "hactoberfest-accepted" instead of "Hactoberfest-Accepted" as it mentioned in Hacktoberfest 2024 rules. Kindly consider this. Thank you!

image

**Comment by AnkitMajee** [comment]
Wait it would take 15 min 30 mins to reflect the change

**Comment by AnkitMajee** [comment]
Also @neyhere07 Just to confirm did your PR showed on your hacktoberfest account.

**Comment by neyhere07** [comment]
> Also @neyhere07 Just to confirm did your PR showed on your hacktoberfest account.

Yes it's showing.

**Pull request merged**
